//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Country
    {
        public int Id { get; set; }
        public int Export_Id { get; set; }
        public int Country_Id { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Export Export { get; set; }
    }
}
