//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LicenseManagerEntities : DbContext
    {
        public LicenseManagerEntities()
            : base("name=LicenseManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Export> Exports { get; set; }
        public virtual DbSet<Export_Country> Export_Country { get; set; }
        public virtual DbSet<Export_Item> Export_Item { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<License_Country> License_Country { get; set; }
        public virtual DbSet<License_Item> License_Item { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
